### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by HLEBYSEKsh** [Everstorm1/BetterDiscord_AutoInstaller#1]
When starting BetterDiscordAutoInjector, error 0xc000007b appears. Trying to reinstall Visual C++ did not help.

**Comment by Everstorm1** [comment]
I updated the BetterDiscordAutoInjector.exe (recompiled the autoinstaller.cpp with static links and specifically to x64 systems), so try again, it might work now.


If not:
I did some research and it looks like there are many possible things that cause that problem. Try running the .exe with admin privileges (since the code tries to terminate all running Discord processes and then injects BD).

Also you could try compiling the code yourself. Given that you simply downloaded the main folder from this repo and all folders are in the place they should be (AND you added your name to the finder.txt as that would yield an error as well) you could try to run "g++ -o BetterDiscordAutoInjector .\autoInstaller.cpp" for example from within the folder in which the autoInstaller.cpp is located and then run the created .exe with admin privileges.

Hope this resolves it, otherwise I will have to do more research.

**Comment by HLEBYSEKsh** [comment]
Previously, when trying to install, there were errors due to missing dll files. Then I just installed them and did not pay attention to it, but they were probably damaged. Today, I re-downloaded all the dll files and the error disappeared.

I don't know if this will be interesting, but I decided to check if the problem was in the user name. It was entered correctly, then I deliberately wrote it incorrectly, but the error did not follow.
